# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain


endpoints:
  shutdown:
    enabled:  true
  restart:
    enabled: true

spring:
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console      # Custom H2 Console URL

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
    #  ddl-auto: none

  main:
    banner-mode: "off"